apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-instance
  labels:
    app: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: localhost:5000/chat-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: chat-variables
        env:
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: chat-app-variables
              key: db-database
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: chat-app-variables
              key: db-app-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chat-app-secrets
              key: db-app-password
        - name: JWT_RSA_PRIVATE
          valueFrom:
            secretKeyRef:
              name: chat-app-jwt-keys
              key: private
        - name: JWT_RSA_PUBLIC
          valueFrom:
            secretKeyRef:
              name: chat-app-jwt-keys
              key: public
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-variables
data:
  DB_URL: 'jdbc:postgresql://postgres-0.postgres-service:5432/postgres'
  DB_HOST: postgres-service
  DB_PORT: '5432'

  REDIS_HOST: localhost
  REDIS_PORT: '6379'
  REDIS_DATABASE: '0'

  KAFKA_HOST: kafka-service:9092
  KAFKA_UPDATE_TOPIC: chat-updates
  KAFKA_MESSAGE_PARTITION: '0'
  KAFKA_ERROR_PARTITION: '1'
  KAFKA_CHATROOM_PARTITION: '2'
  KAFKA_USER_LIST_PARTITION: '3'

  MESSAGE_DESTINATION: message
  MESSAGE_HISTORY_DESTINATION: message-history 
  ERROR_DESTINATION: error
  CHATROOM_DESTINATION: chatroom
  CHATROOM_USERS_DESTINATION: chat-users
